version: "3.3"

services:
  server_api1:
    image: tuannadldev/goapi:1.4
    hostname: go-api-1.com.vn
    ports:
      - 3001:3000
    deploy:
      replicas: 5
      resources:
        limits:
          cpus: '0.5'
          memory: '150MB'
        reservations: # gioi han toi thieu
          cpus: '0.25'
          memory: '50MB'
      restart_policy:
        condition: on-failure
    networks:
      - mynetworkoverlayall
  server_api2:
    image: tuannadldev/goapi:1.3
    hostname: go-api-2.com.vn
    ports:
      - 3002:3000
    deploy:
      replicas: 5
      resources:
        limits:
          cpus: '0.5'
          memory: '150MB'
        reservations: # gioi han toi thieu
          cpus: '0.25'
          memory: '50MB'
      restart_policy:
        condition: on-failure
    networks:
      - mynetworkoverlayall

  mysqldb:
    image: mysql:5.7
    restart: always
    hostname: mysqlhost.dev
    environment:
      - "MYSQL_ROOT_PASSWORD=admin"
      - "MYSQL_DATABASE=golangdemo"
    ports:
      - "3306:3306"
    volumes:
      - "./rdbmyssql/mysql56:/var/lib/mysql"
    networks:
      - mynetworkoverlayall
    deploy:
      placement:
        constraints:
          - node.role == manager

networks:
  mynetworkoverlayall:
    driver: overlay


